---
- name: Install dependencies
  yum: name={{ item }} state=installed
  with_items: shadowsocks_dependencies

- name: Install pip
  easy_install: name=pip

- name: Add the shadowsocks user
  user: name=shadowsocks
        home={{ shadowsocks_home }}
        shell=/sbin/nologin
        comment="Shadowsocks User"

- name: Install Shadowsocks
  pip: name=shadowsocks

- name: Check if config exists
  stat: path={{ shadowsocks_home }}/shadowsocks.json
  register: ssconfig

- debug: msg="{{ shadowsocks_home }}/shadowsocks.json exists, skipping generate new password."
  when: ssconfig.stat.exists == True

- name: Generate a random password
  command: openssl rand -base64 18
  register: shadowsocks_password
  when: ssconfig.stat.exists == False

- name: Generate config file
  template: src=shadowsocks.json
            dest={{ shadowsocks_home }}/shadowsocks.json
            owner=shadowsocks
            group=shadowsocks
            mode=0640
  notify: restart shadowsocks
  when: ssconfig.stat.exists == False

- name: Generate init script
  template: src=shadowsocks.init
            dest=/etc/init.d/shadowsocks
            owner=root
            group=root
            mode=0755

- name: Start and enable service
  service: name=shadowsocks state=started enabled=yes
